name: Test Action
run-name: ${{ github.actor }} is testing this action
on: [push]
jobs:
  test-job:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main'}}
    steps:
      - run: echo "Hello World"
      - run: ssh ubuntu@13.51.199.65 
